[project]
name = "chill"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "click>=8.3.1",
    "textual>=8.2.1",
]

[tool.setuptools]
py-modules = ["main", "chill", "db", "gui", "utils"]

[dependency-groups]
dev = [
    "textual-dev>=1.8.0",
]

[project.scripts]
chillbek = "main:cli"
