[project]
name = "chill"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "click>=8.3.1",
    "cryptocode>=0.1",
    "cryptography>=46.0.5",
]

[tool.setuptools]
py-modules = ["main", "chill", "chill_init"]

[project.scripts]
chilling = "main:cli"
ch="main:cli"
